In [12]:
def _pdist(a, b):
    a = np.asarray(a) 
    b = np.asarray(b)
    if len(a) == 0 or len(b) == 0:
        return np.zeros((len(a), len(b)))
    a2 = np.square(a).sum(axis=1) 
    b2 = np.square(b).sum(axis=1) 
    r2 = -2. * np.dot(a, b.T) + a2[:, None] + b2[None, :]
    print(r2)
    r2 = np.clip(r2, 0., float(np.inf))
    return r2

In [10]:
import numpy as np

In [15]:
distances = _pdist(np.array([[1, 2, 3], [3, 4, 5]]), np.array([[3, 4, 5], [3, 14, 5], [5, 6, 7]]))
np.maximum(0.0, distances.min(axis = 0))

[[14 50]]
[ 50 230 110]
[[ 12. 152.  48.]
 [  0. 100.  12.]]


array([  0., 100.,  12.])

In [16]:
a = np.array([[1, 2, 3], [3, 4, 5]])
a.prod(axis=1)

array([ 6, 60])